### ISSUE TITLE
New interface: SQL

### ISSUE THREAD

**Issue by dmarcelino** [balderdashy/waterline-adapter-tests#40]
There are 2 parts to this:

1. One common offending test on several adapters (sails-memory, sails-disk, sails-redis and sails-mongo) is: *Semantic Interface .find() should escape attribute names to prevent SQL injection attacks*. These adapters do not handle SQL so this test probably does not belong in the **Semantic** Interface. **Solution:** move this test to a new "SQL" interface which SQL adapters would implement. This immediately solves the broken test on those 4 adapters.

2. Assuming we do point 1, why not add something more to the SQL interface? All official and some unofficial SQL adapters support the method `.query(query, data, cb)` ([sails-postgresql](https://github.com/balderdashy/sails-postgresql/blob/master/lib/adapter.js#L99), [sails-mysql](https://github.com/balderdashy/sails-mysql/blob/master/lib/adapter.js#L87), [sails-sqlserver](https://github.com/cnect/sails-sqlserver/blob/master/lib/adapter.js#L260) and [sails-orientdb](https://github.com/appscot/sails-orientdb/blob/master/lib/adapter.js#L392)) so we could make this official and become mandatory for SQL adapters. We probably can't enforce a standard for the output as SQL query can return all sorts of things but we could at least enforce the convention on the method name to invoke a SQL query.

I believe this would be a good way of tidying up these loose ends.

Given the positive feedback, here is a possible strategy to go ahead with this:
 - [x] add sql interface to waterline-adapter-tests moving the SQL injection test: PR #41;
 - [x] update the [Adapter Interface Specification](https://github.com/balderdashy/sails-docs/blob/master/contributing/adapter-specification.md): balderdashy/sails-docs#452
 - [x] update sails-mysql adapter to implement the SQL interface: balderdashy/sails-mysql#205
 - [x] Fix adapter tests #48
 - [x] Release waterline-adapter-tests (`0.10.10`)
 - [x] update sails-postgresql adapter to implement the SQL interface: balderdashy/sails-postgresql#145

cc: @particlebanana, @tjwebb, @devinivy

**Comment by tjwebb** [comment]
I like this. For a project I'm working on, I'm building what's basically a `describeAll()` function which lists the available tables from `information_schema`. It'd be nice to incorporate this type of functionality in sql-like adapters which could support it.

**Comment by devinivy** [comment]
Yes, this is just as we talked about it on chat, and it still sounds good!  The sql-specific test really bugged me for some reason.  Will feel good to separate it out.  Perhaps other methods could be, 

1. Locking for reading/writing
2. `upsert` (update or insert)
3. Something for query logging/debugging
4. Methods looking forward to migrations?

**Comment by dmarcelino** [comment]
@tjwebb, how would `.describeAll()` differ from something like:
```javascript
// assuming an array with all waterline collections names
var results = {};
collections.forEach(function(collection){
  adapter.describe(collection, function(err, definition){
    results[collection] = definition;
  });
});
```
Are the results the same as waterline definitions or are the results SQL specific?

I would be careful enforcing too much in this interface because there are differences between SQL implementations. For example, OrientDB speaks SQL but it does not have JOINs or an `information_schema` table given it's graph/document and java natures. But it's definitely worth the discussion!

@devinivy, I believe migrations is something more generic than SQL, I would love for waterline to offer a common interface (implementation specific to each adapter) for that. Maybe something inspired in [sails-migrations](https://github.com/BlueHotDog/sails-migrations/)?

**Comment by tjwebb** [comment]
describeAll would include tables which are not yet defined as Waterline
collections

**Comment by dmarcelino** [comment]
I see, that makes sense (all my tables are created by waterline so I sometimes forget DBs can have stuff that doesn't exist in waterline :smile: ).

**Comment by devinivy** [comment]
I suggest that for now we just require field name escaping and the `query` method.  Is there anything wrong with adding to the interface in the future?  Worst-case scenario we make additions when WL 0.11 arrives.

**Comment by dmarcelino** [comment]
I agree. We can always add more stuff to the SQL interface in 0.11. For now the priority is to fix the test errors so we can trust the build results.

**Comment by dmarcelino** [comment]
We will need to release waterline-adapter-tests `0.10.9` before we can merge the sails-mysql and sails-postgresql PRs.

**Comment by devinivy** [comment]
The adapter tests were published today.  The sails-postgres PR _failed_, sadly.  This was unexpected.  The issue is that the SQL written in the tests is not correct for postgres and mysql.  Because of the camel-cased table name, postgres requires double-quotes around the table name.  We should adjust the test to be less specific.  This basically requires making the table name lowercase here: https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/sql/support/fixtures/crud.fixture.js#L10
Plus updating the relevant test(s).

**Comment by dmarcelino** [comment]
@devinivy, thanks for the fix! I've updated (and reordered) the tasks in my first post of the thread to reflect the current status of this issue. The MySQL PR can go ahead even before your fix (the advantage being that your fix will be tested in the integration tests (travis ci) against sails-mysql). Fortunately the issue caused is not huge, since the consequence is only the SQL injection test not running against the sails-postgresql temporarily. So none of this is too urgent.

**Comment by devinivy** [comment]
#48 is merged.  @particlebanana if we get another publish, we can merge SQL interface updates on sails-mysql and sails-postgresql without concern.  See related comment https://github.com/balderdashy/sails-postgresql/pull/145#issuecomment-91040478 .

**Comment by particlebanana** [comment]
@devinivy done - `0.10.10`

**Comment by devinivy** [comment]
Saintly!

**Comment by devinivy** [comment]
Merged sails-mysql and sails-postgresql updates :)
Down to https://github.com/balderdashy/sails-docs/pull/452 and any other doc changes.

**Comment by dmarcelino** [comment]
Sweet, great to see this moving along! Thanks

**Comment by dmarcelino** [comment]
All steps concluded, this is now completed. Lets raise new issues for any new functionality to be added to the SQL interface.

**Comment by devinivy** [comment]
:+1: !!
